#@ load("@ytt:overlay","overlay")
#@ load("@ytt:data","data")


#@ if data.values.includeTestingAndScanning:
#@overlay/match by=overlay.all
---
metadata:
  labels:
    #@overlay/match missing_ok=True
    apps.tanzu.vmware.com/has-tests: "true"
#@ end
